application: board-gamers
version: 1
runtime: go
api_version: go1
instance_class: F1
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: automatic
  max_concurrent_requests: 80
handlers:
- url: /_ah/queue/go/delay
  script: _go_app
  login: admin
- url: /_ah/start
  script: _go_app
- url: /_ah/stop
  script: _go_app
- url: /webhook.*
  script: _go_app
- url: /twitter.*
  script: _go_app
- url: /api.*
  script: _go_app
- url: /
  static_files: web/index.html
  upload: /
- url: /
  static_dir: web
skip_files:
- ^(.*/)?.*/node_modules/.*
